language: java
jdk:
    - openjdk8

before_install:
    - chmod +x mvnw

branches:
    only:
        - master

# Travis CI 서버의 HOME
cache:
    directories:
        - '$HOME/.m2/repository'
#script: "mvn clean package"

before_deploy:
    - zip -r spring-boot-board-book-webservice *
    - mkdir -p deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
    - mv spring-boot-board-book-webservice.zip deploy/spring-boot-board-book-webservice.zip # deploy로 zip파일 이동

deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
      secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
      bucket: spring-boot-board # S3 버킷
      region: ap-northeast-2
      skip_cleanup: true
      acl: private # zip 파일 접근을 private으로
      local_dir: deploy # before_deploy에서 생성한 디렉토리
      wait-until-deployed: true

    - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
      secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
      bucket: spring-boot-board # S3 버킷
      key: spring-boot-board-book-webservice.zip # 빌드 파일을 압축해서 전달
      bundle_type: zip
      application: spring-boot-board-book-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
      deployment_group: spring-boot-board-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
      region: ap-northeast-2
      wait-until-deployed: true

notifications:
    slack: mocadevs:0GFPHOOopFep911ZGvAq2eyV
