language: java
jdk:
- openjdk8
before_install:
- chmod +x mvnw
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
before_deploy:
- zip -r spring-boot-board-book-webservice *
- mkdir -p deploy
- mv spring-boot-board-book-webservice.zip deploy/spring-boot-board-book-webservice.zip
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: spring-boot-board
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: deploy
  wait-until-deployed: true
notifications:
  slack:
    secure: bhWrn7AVwBcNmvphrBtEBdmKjvFAkUWf0xM/73ewf9mYe9wVWLSO6Ktp94UIGU08TmHPqz7cBj1a2Iw8ZSsGt+fai/tVxoj/5mZf4hSeWarzDliJRYJepr3qFWtKaPFflTYWVRVC3D1xZSXGz+oQ56sM3eZyFGQEcKgt0XPzImZFor0O+YSXAREyJHSU0h+wqyHehSamu/A6gSZ9TjXwpwCMG2d/9BpxbPzF0IB/Xk3bmJKEOtkgU9AZ1k3SjQa3f9fm+PprdE0XR76Us+T2wTluQFpae+Fk01+6M++pMHa+nRLu0Tec2EpyWggmBpzyI+R/wO94u3mBf5A5V8+y2XyJRsi4G/vmbX2eXkY2uflTD3TY5m6k+bfJXyoI2QoR0C5M+gqBrkXgpzVSIskh9lxxqmLyYgCf/8Ss+xwPCZUkGL+4MKTFpoW4y1AD4AL+qIH07jAvsxpmDtAqLemCBqky9HymtDI4LySgZbUDvB8PJmjcCegCpv7FgXjIuMOpIf5Zl5f08+pAT8gJ3zTWJwmkRFuor694r13ok+iWMrcHFgMFhOq3nNGCN67gnlLXpLJU7wGkbR2U9qGMksmx7GX4PBckVK+R8g8oeoh19ujtk9Ywt3vh8R4LY6wKhDN0/4gm/n/TGC3c/JqBotX68s/cJOIqw/+PbIZVWB9hyCY=
