language: java
jdk:
    - openjdk8

#before_install:
#    - chmod +x mvnw

branches:
    only:
        - master

# Travis CI 서버의 HOME
cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.gradle'
script: "mvn clean compile"
notifications:
    slack: mocadevs:0GFPHOOopFep911ZGvAq2eyV
