spring:
    jpa:
#        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    h2:
        console:
            enabled: true

    devtools:
        livereload:
            enabled: true
    freemarker:
        cache: false

    profiles:
        include: oauth

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
server:
    port: 8090
