spring:
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
        hikari:
            jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
    h2:
        console:
            enabled: true
    devtools:
        livereload:
            enabled: true
    freemarker:
        cache: false
    profiles:
        include: oauth
    session:
        store-type: jdbc

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
server:
    port: 8090
